# Generated by Django 3.2 on 2021-05-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_link', models.CharField(max_length=250)),
                ('short_link', models.CharField(max_length=50)),
                ('stats', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
