# Generated by Django 3.2 on 2021-05-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('email', models.EmailField(max_length=120, verbose_name='ایمیل')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
